### ISSUE TITLE
vosk-asterisk is  not compatible with Asterisk 13

### ISSUE THREAD

**Issue by aribagorda** [alphacep/vosk-asterisk#21]
res-speech-vosk don't load properly on Asterisk 13. It uses a function (ast_websocket_wait_for_input) and indirectly a class (iostream) that it's only available on Asterisk 16 and Asterisk 17.

Is there any way to use it with Asterisk 13?

Congrats for your excellent work.

**Comment by alaa1124** [comment]
Hello,

please are you find solution for res-speech-vosk that don't load properly on Asterisk 13!!!!!!!!!!!!!
thanks

**Comment by nshmyrev** [comment]
Hey simply upgrade to asterisk 16 it should work great. Version 13 is too old.

**Comment by nshmyrev** [comment]
Between with asterisk 18 you can use Vosk ARI set up see client samples in vosk-server project
