### ISSUE TITLE
installation successful, but no application "SpeechCreate"

### ISSUE THREAD

**Issue by YunzhaoLu** [alphacep/vosk-asterisk#27]
Sorry for the disturbance of possible junior question.

![image](https://user-images.githubusercontent.com/32920296/169645176-69d9a876-8cca-4088-b32d-0818ac4335e1.png)

Seems everything is correct, however, can't call SpeechCreate. Thank you.

**Comment by nshmyrev** [comment]
Check in asterisk load log in the beginning that you load res_speech.so. Check modules.conf that res_speech.so is not blocked.

**Comment by YunzhaoLu** [comment]
Thank you. two things: (1) load 'app_speech_utils'; (2) copy res_speech_vosk.conf.
