### ISSUE TITLE
Error loading module res_http_websocket_fix.so

### ISSUE THREAD

**Issue by rybushkindmitry** [alphacep/vosk-asterisk#3]
Error loading module res_http_websocket_fix.so: /usr/lib64/asterisk/modules/res_websocket_fix.so: undefined symbol:ast_websocket_wait_for_input

asterisk 16.6.2

**Comment by nshmyrev** [comment]
Please update to asterisk master.

**Comment by rybushkindmitry** [comment]
Updated to master (Asterisk GIT-master-ca3c22c5f1)
The error is repeated again

**Comment by nshmyrev** [comment]
What is the error exactly? Did you remove old modules, recompile from clean checkout and reinstall?

res_websocket_fix.so is not our module, is it some external module? Our is called res_http_websocket_fix.so

**Comment by rybushkindmitry** [comment]
Sorry, wrote an invalid file name. I mean res_http_websocket_fix.so
Once again I put together the package, everything worked out. many thanks

**Comment by nshmyrev** [comment]
Ok, let me know how it goes.
