### ISSUE TITLE
Periodic jerks heard when playing voice files through SpeechBackground

### ISSUE THREAD

**Issue by rybushkindmitry** [alphacep/vosk-asterisk#4]
Periodic jerks heard when playing voice files through SpeechBackground.
Asterisk and docker work on the same virtual server(4 core, 12Gb RAM), running on Linux host.

**Comment by gobindabd** [comment]
Yes, I am also facing same problem.

**Comment by nshmyrev** [comment]
I have pushed a fix, please update and test if it solves your issue.

**Comment by nshmyrev** [comment]
@gobindabd said it is fixed
