### ISSUE TITLE
 can anyone help me??

### ISSUE THREAD

**Issue by alaa1124** [alphacep/vosk-asterisk#40]
please, i want to install but i have error, can anyone help me??

**Comment by nshmyrev** [comment]
Sure please provide the details

**Comment by alaa1124** [comment]
> Sure please provide the details

we are using the vox server to transcribe the call audio right after Answer(), still in early media.
How will it be possible to detect an AMD even before answering the call?

GSM operators play the voicemail message without answering the call, hence the importance of transcribing the call even before answering

I will send the audio of the messages that the operators play before forwarding to voicemail

**Comment by nshmyrev** [comment]
Same as #41
