### ISSUE TITLE
can not load the res_speech_vosk.so from asterisk

### ISSUE THREAD

**Issue by voskfa** [alphacep/vosk-asterisk#42]
hello:
I installed it with asterisk-20 and compiled without any error  also edit the modules files and let the modules load. but when I start an asterisk, i can not see the module's name. anything wrong? 

thanks!

**Comment by nshmyrev** [comment]
Yes!

**Comment by voskfa** [comment]
thanks.

**Comment by nshmyrev** [comment]
Let us know how it goes
