### ISSUE TITLE
Not found ./configure, i have in folder only configure.ac

### ISSUE THREAD

**Issue by bottookku** [alphacep/vosk-asterisk#5]
./configure --with-asterisk=/root/asterisk --prefix=/root/soxx
-bash: ./configure: No such file or directory

if i run /configure.ac then i give this log

/configure.ac --with-asterisk=/root/asterisk --prefix=/root/soxx
./configure.ac: line 1: syntax error near unexpected token `asterisk-vosk,'
./configure.ac: line 1: `AC_INIT(asterisk-vosk, 0.3.7)'

**Comment by nshmyrev** [comment]
You need to run `bootstrap` first
